sudo: required
services:
  - docker

before_install:
  - docker build -t temple4b/easybanking .

script:
  - docker run -e CI=true temple4b/easybanking npm run test

after_success:
  - docker build -t temple4b/easybanking -f .
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push temple4b/easybanking
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "frontend"
#   env: "frontend-env"
#   bucket_name: "elasticbeanstalk-us-east-1-617631581212"
#   bucket_path: "frontend"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
