sudo: required
services:
  - docker

before_install:
  - docker build -t easybanking -f Dockerfile.dev .

script:
  - docker run -e CI=true easybanking npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-617631581212"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS-Access key
  secret_access_key: $AWS-secret
