version: "3"
services:
  easy-banking:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    command: ["npm", "run", "test"]
